language: android
install: true
os:
  -linux
  -osx
android:
  components:
    - android-27
    - build-tools-26.0.2
before_install:
  - yes | sdkmanager "build-tools;27.0.3"
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew -x android:assemble assemble          ; fi

addons:
  apt:
    packages:
      - oracle-java8-set-default

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
